// <auto-generated />
using System;
using LearnProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LearnProject.Migrations
{
    [DbContext(typeof(KKWebAPIDbContext))]
    [Migration("20251129055709_MigrationName")]
    partial class MigrationName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LearnProject.Model.Domain.Diffculty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Diffculties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-4789-9012-3456789abcde"),
                            Name = "Easy"
                        },
                        new
                        {
                            Id = new Guid("b2c3d4e5-f6a1-4890-0123-456789abcdef"),
                            Name = "Medium"
                        },
                        new
                        {
                            Id = new Guid("c3d4e5f6-a1b2-4901-1234-56789abcdef0"),
                            Name = "Hard"
                        });
                });

            modelBuilder.Entity("LearnProject.Model.Domain.Region", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegionImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d1e2f3a4-b5c6-4718-9012-111111111111"),
                            Code = "AKL",
                            Name = "Auckland",
                            RegionImageUrl = "https://example.com/images/auckland.jpg"
                        },
                        new
                        {
                            Id = new Guid("e2f3a4b5-c6d7-4829-9012-222222222222"),
                            Code = "WLG",
                            Name = "Wellington",
                            RegionImageUrl = "https://example.com/images/wellington.jpg"
                        },
                        new
                        {
                            Id = new Guid("f3a4b5c6-d7e8-4930-9012-333333333333"),
                            Code = "CAN",
                            Name = "Canterbury",
                            RegionImageUrl = "https://example.com/images/canterbury.jpg"
                        },
                        new
                        {
                            Id = new Guid("a4b5c6d7-e8f9-5041-9012-444444444444"),
                            Code = "OTA",
                            Name = "Otago",
                            RegionImageUrl = "https://example.com/images/otago.jpg"
                        },
                        new
                        {
                            Id = new Guid("b5c6d7e8-f9a1-5152-9012-555555555555"),
                            Code = "BOP",
                            Name = "Bay of Plenty",
                            RegionImageUrl = "https://example.com/images/bay-of-plenty.jpg"
                        });
                });

            modelBuilder.Entity("LearnProject.Model.Domain.Walk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DiffcultyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("LengthInKm")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("WalkImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DiffcultyId");

                    b.HasIndex("RegionId");

                    b.ToTable("Walks");
                });

            modelBuilder.Entity("LearnProject.Model.Domain.Walk", b =>
                {
                    b.HasOne("LearnProject.Model.Domain.Diffculty", "Diffculty")
                        .WithMany()
                        .HasForeignKey("DiffcultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LearnProject.Model.Domain.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Diffculty");

                    b.Navigation("Region");
                });
#pragma warning restore 612, 618
        }
    }
}
